apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: elasticsearch
    releaseName: elasticsearch
    repo: https://helm.elastic.co
    version: $(ChartVersion)
    includeCRDs: true
    namespace: elasticsearch
    valuesFile: values.yaml

helmGlobals:
  chartHome: charts