on:
  push:
    branches:
      - master
  pull_request:

jobs:
  create-deployment-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: imranismail/setup-kustomize@v2
      - name: Run Kustomise
        shell: bash
        run: |
            echo "Testing"
            ls -alh
            chmod +x run.sh
            sh run.sh --update-version=false 
          
