on:
  push:
    branches:
      - master
      - pr

  pull_request:
    types:
      labeled

jobs:
  version-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: imranismail/setup-kustomize@v2
      - name: Get Labels
        if: ${{ github.event.label.name }}
        id: labels
        run: |
           echo ${{ github.event.label.name }}
      - name: Update Chart Version
        shell: bash
        if: ${{ github.event.label.name }}
        env:
          RELEASE: ${{ github.event.label.name }}
        run: |
            echo "Testing"
            ls -alh
            echo $RELEASE
            kustomize version
            chmod +x run.sh
            ./run.sh --release=$RELEASE --update-version=true
        working-directory: charts/elasticsearch
        

      - name: Run Kustomize Build On Current Version
        shell: bash
        run: |
            chmod +x run.sh
            ./run.sh --update-version=false
        working-directory: charts/elasticsearch
        
            

        
          
