name: CI
on:
  push:
    branches:
      - master
      - pr

  pull_request:
    types:
      labeled

jobs:
  version-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      CHART_PATH: ./charts/elasticsearch/Chart.yaml
    steps:
      - uses: actions/checkout@v3
      - uses: imranismail/setup-kustomize@v2
      - name: Get Labels
        if: ${{ github.event.label.name }} && github.event_name == 'pull_request'
        id: labels
        run: |
           echo ${{ github.event.label.name }}
      - name: Update Chart Version - ${{ github.event.label.name }}-Update
        shell: bash
        if: (${{ github.event.label.name }} && github.event_name == 'pull_request') && success()
        env:
          RELEASE: ${{ github.event.label.name }}
        run: |
            chmod +x run.sh
            ./run.sh --chart-path=$CHART_PATH --release=$RELEASE --update-version=true
        
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: success()
        with:
          commit_message: Chart Version Updated successfully!

      - name: Run Kustomize Build On Current Version
        shell: bash
        run: |
            chmod +x run.sh
            ./run.sh --chart-path=$CHART_PATH --update-version=false
        
            

        
          
