on:
  push:
    branches:
      - master
  pull_request:
    types:
      labeled

jobs:
  version-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: imranismail/setup-kustomize@v2
      - name: Get Labels
        id: labels
        run: |
           echo ${{ github.event.label.name }}
           echo "::set-output name=labels::${{ toJson(github.event.pull_request.labels) }}"
      - name: Display Labels
        run: |
          echo "Labels: ${{ steps.labels.outputs.labels }}"
           
      - name: Run Kustomise
        shell: bash
        run: |
            echo "Testing"
            ls -alh
            kustomize version
            chmod +x run.sh
            ./run.sh --release=patch --update-version=true

        
          
